
import { SkillCategory, SkillProps } from "@/@types/stack";
import {
    SiReact,
    SiNextdotjs,
    SiTypescript,
    SiTailwindcss,
    SiNodedotjs,
    SiPrisma,
    SiJavascript,
    SiPostgresql,
    SiGit,
    SiDocker,
    SiSupabase,
    SiFirebase,
    SiHtml5,
    SiVuedotjs,
    SiCss,
    SiBootstrap,
    SiAstro,
    SiVite,
    SiShadcnui,
    SiReacttable,
    SiReacthookform,
    SiReactrouter,
    SiAxios,
    SiZod,
    SiRedux,
    SiFramer,
    SiExpress,
    SiNestjs,
    SiPhp,
    SiLaravel,
    SiKotlin,
    SiJetpackcompose,
    SiGo,
    SiGithub,
    SiNpm,
    SiJest,
    SiMongodb,
    SiMysql,
    SiAib,
    SiReactquery,
    SiSanity,
} from "react-icons/si";

export const skillCategories: SkillCategory[] = [
    {
        color: "from-blue-400 to-blue-600",
        name: "React",
        icon: <SiReact />,
        description: "Modern UI library",
    },
    {
        color: "from-gray-800 to-black",
        name: "Next.js",
        icon: <SiNextdotjs />,
        description: "React framework",
    },
    {
        color: "from-blue-500 to-blue-700",
        name: "TypeScript",
        icon: <SiTypescript />,
        description: "Type-safe JavaScript",
    },
    {
        color: "from-cyan-400 to-blue-500",
        name: "Tailwind CSS",
        icon: <SiTailwindcss />,
        description: "Utility CSS framework",
    },
    {
        color: "from-green-500 to-green-700",
        name: "Node.js",
        icon: <SiNodedotjs />,
        description: "JS runtime",
    },
    {
        color: "from-cyan-500 to-blue-600",
        name: "Prisma",
        icon: <SiPrisma />,
        description: "ORM for databases",
    },
    {
        color: "from-yellow-300 to-yellow-500",
        name: "JavaScript",
        icon: <SiJavascript />,
        description: "Core language",
    },
    {
        color: "from-blue-500 to-blue-700",
        name: "PostgreSQL",
        icon: <SiPostgresql />,
        description: "Relational DB",
    },
    {
        color: "from-orange-500 to-red-600",
        name: "Git",
        icon: <SiGit />,
        description: "Version control",
    },
    {
        color: "from-blue-400 to-blue-600",
        name: "Docker",
        icon: <SiDocker />,
        description: "Containerization",
    },
    {
        color: "from-emerald-400 to-teal-600",
        name: "Supabase",
        icon: <SiSupabase />,
        description: "Backend as a Service",
    },
    {
        name: "Firebase",
        color: "from-yellow-300 to-orange-500",
        icon: <SiFirebase/>,
        description: "Realtime DB & Auth",
    },
    {
        name: "Framer Motion",
        color: "from-sky-300 to-orange-500",
        icon: <SiFramer/>,
        description: "Realtime DB & Auth",
    },
    {
        name: "Go",
        color: "from-blue-300 to-blue-500",
        icon: <SiGo/>,
        description: "Realtime DB & Auth",
    },
];

const iconSize = 30;

export const STACKSPROJECTS: SkillProps = {
  HTML: {
    icon: <SiHtml5 size={iconSize} />,
    background: "bg-orange-500",
    color: "text-orange-500",
    isActive: true,
  },
  CSS: {
    icon: <SiCss size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  Bootstrap: {
    icon: <SiBootstrap size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: true,
  },
  TailwindCSS: {
    icon: <SiTailwindcss size={iconSize} />,
    background: "bg-sky-400",
    color: "text-sky-400",
    isActive: true,
  },
  JavaScript: {
    icon: <SiJavascript size={iconSize} />,
    background: "bg-yellow-400",
    color: "text-yellow-400",
    isActive: true,
  },
  TypeScript: {
    icon: <SiTypescript size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  "Vue.js": {
    icon: <SiVuedotjs size={iconSize} />,
    background: "bg-green-400",
    color: "text-green-400",
    isActive: false,
  },
  "React.js": {
    icon: <SiReact size={iconSize} />,
    background: "bg-cyan-400",
    color: "text-cyan-400",
    isActive: true,
  },
  Vite: {
    icon: <SiVite size={iconSize} />,
    background: "bg-purple-500",
    color: "text-purple-500",
    isActive: true,
  },
  "Astro.js": {
    icon: <SiAstro size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: true,
  },
  "Shadcn UI": {
    icon: <SiShadcnui size={iconSize} />,
    background: "bg-neutral-800",
    color: "text-neutral-800",
    isActive: true,
  },

  "TanStack": {
    icon: <SiReactquery size={iconSize} />,
    background: "bg-amber-500",
    color: "text-amber-500",
    isActive: true,
  },
  "React Table": {
    icon: <SiReacttable size={iconSize} />,
    background: "bg-rose-600",
    color: "text-rose-600",
    isActive: false,
  },
  "React Hook Form": {
    icon: <SiReacthookform size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: false,
  },
  "React Router": {
    icon: <SiReactrouter size={iconSize} />,
    background: "bg-red-500",
    color: "text-red-500",
    isActive: false,
  },
  Axios: {
    icon: <SiAxios size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: true,
  },
  Zod: {
    icon: <SiZod size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: true,
  },
  "Framer Motion": {
    icon: <SiFramer size={iconSize} />,
    background: "bg-yellow-400",
    color: "text-yellow-400",
    isActive: true,
  },
  Redux: {
    icon: <SiRedux size={iconSize} />,
    background: "bg-violet-500",
    color: "text-violet-500",
    isActive: true,
  },
  Prisma: {
    icon: <SiPrisma size={iconSize} />,
    background: "bg-teal-500",
    color: "text-teal-500",
    isActive: true,
  },
  "Next.js": {
    icon: <SiNextdotjs size={iconSize} />,
    background: "bg-neutral-800",
    color: "dark:text-neutral-50",
    isActive: true,
  },
  "Express.js": {
    icon: <SiExpress size={iconSize} />,
    background: "bg-neutral-800",
    color: "text-neutral-800",
    isActive: true,
  },
  "Nest.js": {
    icon: <SiNestjs size={iconSize} />,
    background: "bg-rose-600",
    color: "text-rose-600",
    isActive: false,
  },
  Go: {
    icon: <SiGo size={iconSize} />,
    background: "bg-sky-500",
    color: "text-sky-500",
    isActive: true,
  },
  PHP: {
    icon: <SiPhp size={iconSize} />,
    background: "bg-indigo-400",
    color: "text-indigo-400",
    isActive: true,
  },
  Laravel: {
    icon: <SiLaravel size={iconSize} />,
    background: "bg-red-700",
    color: "text-red-700",
    isActive: true,
  },
  Kotlin: {
    icon: <SiKotlin size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: true,
  },
  "Jetpack Compose": {
    icon: <SiJetpackcompose size={iconSize} />,
    background: "bg-cyan-800",
    color: "text-cyan-800",
    isActive: true,
  },
  PostgreSql: {
    icon: <SiPostgresql size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  },
  MySql: {
    icon: <SiMysql size={iconSize} />,
    background: "bg-cyan-700",
    color: "text-cyan-700",
    isActive: true,
  },
  MongoDb: {
    icon: <SiMongodb size={iconSize} />,
    background: "bg-green-600",
    color: "text-green-600",
    isActive: false,
  },
  Firebase: {
    icon: <SiFirebase size={iconSize} />,
    background: "bg-amber-500",
    color: "text-amber-500",
    isActive: true,
  },
  Supabase: {
    icon: <SiSupabase size={iconSize} />,
    background: "bg-emerald-500",
    color: "text-emerald-500",
    isActive: true,
  },
  Jest: {
    icon: <SiJest size={iconSize} />,
    background: "bg-pink-600",
    color: "text-pink-600",
    isActive: false,
  },
  Docker: {
    icon: <SiDocker size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-500",
    isActive: true,
  },
  AI: {
    icon: <SiAib size={iconSize} />,
    background: "bg-fuchsia-700",
    color: "text-fuchsia-700",
    isActive: false,
  },
  Npm: {
    icon: <SiNpm size={iconSize} />,
    background: "bg-red-700",
    color: "text-red-500",
    isActive: true,
  },
  Github: {
    icon: <SiGithub size={iconSize} />,
    background: "bg-slate-800",
    color: "text-neutral-50",
    isActive: true,
  },
  Sanity: {
    icon: <SiSanity size={iconSize} />,
    background: "bg-blue-500",
    color: "text-blue-500",
    isActive: true,
  }
};
