/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link_demo?: string;
  link_github?: string;
  stacks?: Array<string>;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  is_show?: boolean;
  is_featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Career = {
  _id: string;
  _type: "career";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  position?: string;
  company?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  locationType?: "onsite" | "remote" | "hybrid";
  type?: "full-time" | "part-time" | "contract" | "internship" | "freelance";
  startDate?: string;
  endDate?: string;
  industry?: string;
  link?: string;
  responsibilities?: Array<string>;
  lessonsLearned?: Array<string>;
  impact?: Array<string>;
  isShow?: boolean;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  credentialId?: string;
  issuingOrganization?: string;
  type?: "certificate" | "award" | "competition";
  category?: "technology" | "education" | "competition" | "others";
  urlCredential?: string;
  issueDate?: string;
  expirationDate?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isShow?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Career
  | Achievement
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../app/sanity/queries.ts
// Variable: allAchievementQuery
// Query: *[_type == "achievement" && isShow == true]{    _id,    name,    slug,    credentialId,    issuingOrganization,    type,    category,    urlCredential,    issueDate,    expirationDate,    image  } | order(issueDate desc)
export type AllAchievementQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  credentialId: string | null;
  issuingOrganization: string | null;
  type: "award" | "certificate" | "competition" | null;
  category: "competition" | "education" | "others" | "technology" | null;
  urlCredential: string | null;
  issueDate: string | null;
  expirationDate: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ../app/sanity/queries.ts
// Variable: achievementBySlugQuery
// Query: *[_type == "achievement" && slug.current == $slug][0]{    _id,    name,    slug,    credentialId,    issuingOrganization,    type,    category,    urlCredential,    issueDate,    expirationDate,    image  }
export type AchievementBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  credentialId: string | null;
  issuingOrganization: string | null;
  type: "award" | "certificate" | "competition" | null;
  category: "competition" | "education" | "others" | "technology" | null;
  urlCredential: string | null;
  issueDate: string | null;
  expirationDate: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: ../app/sanity/queries.ts
// Variable: allCareerQuery
// Query: *[_type == "career" && isShow == true]{    _id,    position,    company,    logo,    location,    locationType,    type,    startDate,    endDate,    industry,    link,    responsibilities,    lessonsLearned,    impact  } | order(startDate desc)
export type AllCareerQueryResult = Array<{
  _id: string;
  position: string | null;
  company: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  location: string | null;
  locationType: "hybrid" | "onsite" | "remote" | null;
  type:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | null;
  startDate: string | null;
  endDate: string | null;
  industry: string | null;
  link: string | null;
  responsibilities: Array<string> | null;
  lessonsLearned: Array<string> | null;
  impact: Array<string> | null;
}>;

// Source: ../app/sanity/queries.ts
// Variable: careerByIdQuery
// Query: *[_type == "career" && _id == $id][0]{    _id,    position,    company,    logo,    location,    locationType,    type,    startDate,    endDate,    industry,    link,    responsibilities,    lessonsLearned,    impact  }
export type CareerByIdQueryResult = {
  _id: string;
  position: string | null;
  company: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  location: string | null;
  locationType: "hybrid" | "onsite" | "remote" | null;
  type:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | null;
  startDate: string | null;
  endDate: string | null;
  industry: string | null;
  link: string | null;
  responsibilities: Array<string> | null;
  lessonsLearned: Array<string> | null;
  impact: Array<string> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "achievement" && isShow == true]{\n    _id,\n    name,\n    slug,\n    credentialId,\n    issuingOrganization,\n    type,\n    category,\n    urlCredential,\n    issueDate,\n    expirationDate,\n    image\n  } | order(issueDate desc)\n': AllAchievementQueryResult;
    '\n  *[_type == "achievement" && slug.current == $slug][0]{\n    _id,\n    name,\n    slug,\n    credentialId,\n    issuingOrganization,\n    type,\n    category,\n    urlCredential,\n    issueDate,\n    expirationDate,\n    image\n  }\n': AchievementBySlugQueryResult;
    '\n  *[_type == "career" && isShow == true]{\n    _id,\n    position,\n    company,\n    logo,\n    location,\n    locationType,\n    type,\n    startDate,\n    endDate,\n    industry,\n    link,\n    responsibilities,\n    lessonsLearned,\n    impact\n  } | order(startDate desc)\n': AllCareerQueryResult;
    '\n  *[_type == "career" && _id == $id][0]{\n    _id,\n    position,\n    company,\n    logo,\n    location,\n    locationType,\n    type,\n    startDate,\n    endDate,\n    industry,\n    link,\n    responsibilities,\n    lessonsLearned,\n    impact\n  }\n': CareerByIdQueryResult;
  }
}
